name: compile

on: [push]

jobs:
  pyinstaller-build:
    runs-on: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          pyinstaller_ver: '==6.10.0'
          spec: 'src/build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'perv-tok'
          options: --onefile, --name "perv-tok", --windowed